### ISSUE TITLE
Fatal error on wordpress 6.1

### ISSUE THREAD

**Issue by thoyan0nymous** [qodrorid/wppg#5]
Fatal error:
Uncaught Error: Call to undefined method wppg_db::placeholder_escape() in /wordpress/wp-includes/class-wp-query.php:4751
Stack trace:
#0 /wordpress/wp-includes/class-wp-query.php(3110): WP_Query->generate_cache_key(Array, '\n\t\t\tSELECT wp...')
#1 /wordpress/wp-includes/class-wp-query.php(3726): WP_Query->get_posts()
#2 /wordpress/wp-includes/class-wp-query.php(3858): WP_Query->query(Array)
#3 /wordpress/wp-includes/block-template-utils.php(931): WP_Query->__construct(Array)
#4 /wordpress/wp-includes/blocks/template-part.php(201): get_block_templates(Array, 'wp_template_par...')
#5 /wordpress/wp-includes/blocks/template-part.php(241): build_template_part_block_instance_variations()
#6 /wordpress/wp-includes/blocks/template-part.php(252): build_template_part_block_variations()
#7 /wordpress/wp-includes/class-wp-hook.php(308): register_block_core_template_pa in /wordpress/wp-includes/class-wp-query.php on line 4751

Sorry about just reporting the issue.

**Comment by thoyan0nymous** [comment]
Release 6.1.1 works so that close the issue myself.

**Comment by thoyan0nymous** [comment]
No, it was not.

Fatal error:
Uncaught Error: Call to undefined method wppg_db::placeholder_escape() in /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp-query.php:4774
Stack trace:
#0 /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp-query.php(3125): WP_Query->generate_cache_key(Array, '\n\t\t\tSELECT SQL_...')
#1 /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp-query.php(3749): WP_Query->get_posts()
#2 /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp.php(663): WP_Query->query(Array)
#3 /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp.php(783): WP->query_posts() 
#4 /data/share/nginx/wordpress-6.1.1/wp-includes/functions.php(1332): WP->main(Array)
#5 /data/share/nginx/wordpress-6.1.1/wp-admin/includes/post.php(1245): wp(Array)
#6 /data/share/nginx/wordpress-6.1.1/wp-admin/includes/class-wp-posts-list-table.php(165): wp_edit_posts_query()
#7 /data/share/nginx/wordpress-6.1.1/wp-admin/edit.php(235): WP_Posts_List_Table->prepare_items()
#8 {main} thrown in /data/share/nginx/wordpress-6.1.1/wp-includes/class-wp-query.php on line 4774

There has been a critical error on this website. Please check your site admin email inbox for instructions.
